# Generated by Django 5.0.7 on 2024-07-09 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('gestores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_pago', models.DateTimeField()),
                ('monto', models.PositiveIntegerField()),
                ('abonos', models.PositiveIntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestores.gestor')),
            ],
        ),
    ]
